import "../styles/modern-normalize.css";
import "../styles/style.css";
// component
import "../styles/components/header.css";
import "../styles/components/hero.css";
import "../styles/components/choose-us.css";
import "../styles/components/take-control.css";
import "../styles/components/money.css";
import "../styles/components/expertise.css";
import "../styles/components/world-of-fisdom.css";
import "../styles/components/wealth.css";
import "../styles/components/trusted.css";
import "../styles/components/customers.css";
import "../styles/components/inspires.css";
import "../styles/utils.css";
